services:
  mongodb:
    image: mongo:7.0
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1 >/dev/null" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "27017:27017"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "140MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true