services:
  api-1:
    image: pvssdev/rinha-backend-2025-java-spring-boot-native:0.0.1
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/rinha
    depends_on: [ mongodb ]
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  api-2:
    image: pvssdev/rinha-backend-2025-java-spring-boot-native:0.0.1
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/rinha
    depends_on: [ mongodb ]
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "27017:27017"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "140MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true