services:
  mongodb:
    image: mongo:7.0-jammy
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "27017:27017"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "140MB"

  api-1: &api-1
    image: pvssdev/rinha-backend-2025-java-spring-boot-native:0.0.1
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  api-2:
    <<: *api-1
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true