services:
  api-1:
    build: .
    environment:
      - REDIS_URI=redis://redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "135MB"

  api-2:
    build: .
    environment:
      - REDIS_URI=redis://redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "135MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  redis:
    image: redis:7.2-alpine
    command: redis-server --save "" --appendonly no --maxclients 20000 --maxmemory-policy allkeys-lru
    networks:
      - backend
      - payment-processor
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true