processor.batch.size=100
processor.schedule.every=2s
quarkus.native.container-build=true
quarkus.rest-client."default-processor".url=http://payment-processor-default:8080
quarkus.rest-client."fallback-processor".url=http://payment-processor-fallback:8080
# logs
# 1) root só mostra ERROR+
quarkus.log.level=ERROR
# 2) debug só no scheduler
quarkus.log.category."br.com.pvssdev.infrastructure.scheduler".level=DEBUG
# 3) silencie blocked?thread checker
quarkus.log.category."io.vertx.core.impl.BlockedThreadChecker".level=ERROR
# 4) silencie também timeouts do fault?tolerance e DNS do Netty
quarkus.log.category."io.smallrye.faulttolerance.core.timeout".level=ERROR
quarkus.log.category."io.netty.resolver".level=ERROR