processor.batch.size=100
processor.schedule.every=2s
quarkus.native.container-build=true
quarkus.rest-client."default-processor".url=http://payment-processor-default:8080
quarkus.rest-client."fallback-processor".url=http://payment-processor-fallback:8080
# logs
# 1) raiz só ERROR+ (silencia INFO/DEBUG de bibliotecas)
quarkus.log.level=ERROR
# 2) DEBUG apenas no endpoint de resumo, para acompanhar só esse fluxo
quarkus.log.category."br.com.pvssdev.infrastructure.api.PaymentResource".level=DEBUG
quarkus.log.category."br.com.pvssdev.application.service.PaymentsSummaryService".level=DEBUG
# 3) silencie WARNs do scheduler de health?check e do FaultTolerance
quarkus.log.category."br.com.pvs.inf.sch.HealthCheckScheduler".level=ERROR
quarkus.log.category."io.smallrye.faulttolerance".level=ERROR
# 4) silencie ruído de Vert.x, Hibernate Reactive, etc
quarkus.log.category."io.vertx".level=ERROR
quarkus.log.category."org.hibernate.reactive.pool".level=ERROR