# ------------------------------------------------
# Batch
processor.batch.size=100
processor.schedule.every=2s
# Build
quarkus.native.container-build=true
# External payment?processors
quarkus.rest-client."default-processor".url=http://payment-processor-default:8080
quarkus.rest-client."fallback-processor".url=http://payment-processor-fallback:8080
# ------------------------------------------------
# Reactive Datasource Pool
quarkus.datasource.reactive.url=${QUARKUS_DATASOURCE_REACTIVE_URL:}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.max-size=100
# ------------------------------------------------
# Logging
# 1) tudo ERROR+ por padrão
quarkus.log.level=INFO
# 2) DEBUG apenas na API de resumo
quarkus.log.category."br.com.pvssdev.infrastructure.api.PaymentResource".level=DEBUG
quarkus.log.category."br.com.pvssdev.application.service.PaymentsSummaryService".level=DEBUG
# 3) silencia WARNING de scheduler e fault?tolerance
quarkus.log.category."br.com.pvs.inf.sch.HealthCheckScheduler".level=ERROR
quarkus.log.category."io.smallrye.faulttolerance".level=ERROR
# 4) silencia ruído de Vert.x e Hibernate Reactive pool
quarkus.log.category."io.vertx".level=ERROR
quarkus.log.category."org.hibernate.reactive.pool".level=ERROR
quarkus.log.category."br.com.pvssdev".level=INFO